### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by EgleSc** [DMU-CTEC2902/TeamHorus#36]
As a customer I would like the website to be tested to make sure less errors occur.
and as system coordinators we need to create test plans, so that the developers can do testing for the system.

@FreddyJilson, test plans for: clsMovie, clsStory, clsComment, clsLeague, clsGenre, clsGenreMovie and clsRole
@EgleSc, test plans for: clsActor, clsDirector, clsForum, clsReview, clsUser, clsAdmin and clsDirectorMovie

Here is a link for test plans - https://github.com/DMU-CTEC2902/TeamHorus/blob/master/TestPlan_Format.doc

Thanks.

**Comment by EgleSc** [comment]
Me and Freddie will get some test plans done? Is that fine with you guys?

**Comment by MohammedSheikh** [comment]
Test plans will be very much appreciated as this mean as developers we will be able to start implementing tests straight away as we code. For the test plans, the properties and other elements to be tested should be taken from any diagrams to ensure consistency.

**Comment by FreddyJilson** [comment]
I have uploaded the test plans for the classes/models: Movie, Genre, MovieGenre, Story and Comment.
Here is the link- https://github.com/DMU-CTEC2902/TeamHorus/blob/master/Wiki_Documentation_25thApril2016/Freddy_TestPlans.doc
