### ISSUE TITLE
Create use case diagram and descriptions

### ISSUE THREAD

**Issue by EgleSc** [DMU-CTEC2902/TeamHorus#37]
As a customer I would like to see the main functionality of the system in the form of a use case diagram and descriptions to go along with it.

**Comment by FreddyJilson** [comment]
Use case descriptions for the Admin is completed. Here is the link - https://github.com/DMU-CTEC2902/TeamHorus/blob/master/Wiki_Documentation_25thApril2016/Freddy_AdminUseCaseDescriptions.docx
