### ISSUE TITLE
MANY MANY TO MANY PROBLEMS!!!

### ISSUE THREAD

**Issue by Carvalth** [DMU-CTEC2902/TeamHorus#40]
Many to Many from Movie to Director and many to many for movie to genre!!!

**Comment by EgleSc** [comment]
for movie to genre , for now have the class called movie-genre, so combining the two names until maybe later on thinking of a better name for it.

**Comment by EgleSc** [comment]
and movie director for the movie to director many to many

**Comment by FreddyJilson** [comment]
[https://github.com/DMU-CTEC2902/TeamHorus/blob/master/Issue_40.jpg](url)
