### ISSUE TITLE
Admin Properties

### ISSUE THREAD

**Issue by MohammedSheikh** [DMU-CTEC2902/TeamHorus#45]
Please edit the Admin class diagram to correspond with the following properties in the screenshot.

![adminproperties](https://cloud.githubusercontent.com/assets/16736330/14492663/c5ec7616-0178-11e6-96cb-831154991040.png)

**Comment by EgleSc** [comment]
it ok when you have completed more work near the end of the project then i will be taking a look at the documentation on what to change again. We are working on creating the other documentation for next week.

**Comment by MohammedSheikh** [comment]
OK, but its better to complete it early, as we will be doing it in code anyway.

**Comment by EgleSc** [comment]
As i said we will adjust this later. As we are busy working on other diagrams that need to be done. Rather than changing something many times the final alterations will be made in time for the presentation. As you guys are developers you should focus less on the documentation side of things.

**Comment by MohammedSheikh** [comment]
What other diagrams are you currently working on?

The whole purpose of documentation is so that it is ready so that developers can work from it as the project progresses. It does not matter if the documentation and the diagrams have to be constantly altered as this is part and parcel of any software development lifecycle. But it is definitely better to have it all prepared as normally its would not be acceptable to have diagrams and documentation ready at the END of a project as this would provide no use.

As developers we should be developing based on resources that have already been created so that we do not have to end up focussing on the documentation side of things.
