### ISSUE TITLE
Group meeting and project work

### ISSUE THREAD

**Issue by FreddyJilson** [DMU-CTEC2902/TeamHorus#49]
All team members,

@MwenyaJunior 
@MohammedSheikh 
@Carvalth 
@EgleSc 

A group meeting is scheduled tomorrow at 9:30 am. In this group meeting we will be working on our movie review project and the developers can help each other with their code on improvising it. System analysts will be preparing for the final presentation and other documentation required for the project. We will also be discussing about the changes made in the class diagrams and other requirements.
Hope to see you all tomorrow.

Thanks.

**Comment by MohammedSheikh** [comment]
I will be there at 9.30 as it is imperative that we discuss the next stages of the project as there is a lot of development left to be done.
