### ISSUE TITLE
Combining Diagrams

### ISSUE THREAD

**Issue by EgleSc** [DMU-CTEC2902/TeamHorus#50]
As a developer I would like the diagrams to be combined so that it would be easier to view them.

**Comment by EgleSc** [comment]
Could we create the diagrams on one, I have drawn them by hand but believe it would be best to put them together so it is easier for others to read.

**Comment by FreddyJilson** [comment]
Yes that would be brilliant, but are we talking about the class diagrams or all the diagrams?

**Comment by FreddyJilson** [comment]
All the documentation is combined and can be found on this folder - https://github.com/DMU-CTEC2902/TeamHorus/tree/master/Wiki_Documentation_25thApril2016
