### ISSUE TITLE
An additional table in database

### ISSUE THREAD

**Issue by FreddyJilson** [DMU-CTEC2902/TeamHorus#54]
Developers, 

@Carvalth 
@MohammedSheikh 
@MwenyaJunior 

I think we are missing a tblUsers table in the database for storing the user details. The attributes can be UserID, Name, Password and Email.
thanks.

**Comment by MohammedSheikh** [comment]
This is because the 'User' table is unique in our system as the 'Admin' table inherits from it. For this reason, I am yet to find out how to make the model classes inherit from each other and when I do, I will add it on.

**Comment by FreddyJilson** [comment]
Okay that's fine. Cool, I thought you guys just forgot about that.
