### ISSUE TITLE
Unit Test Error

### ISSUE THREAD

**Issue by MohammedSheikh** [DMU-CTEC2902/TeamHorus#56]
Callum, when running your unit tests, it displays error as I think you may have written two tests with the same name.

![image](https://cloud.githubusercontent.com/assets/16736330/14795658/57b90166-0b21-11e6-983a-7e25ce5fe558.png)

**Comment by Carvalth** [comment]
Thank you for pointing that out, I'll fix it now.
I put one property test group up to demonstrate the unit testing for the presentation

**Comment by MohammedSheikh** [comment]
Thanks for that, hopefully the project should compile now.
