### ISSUE TITLE
Website Image Content

### ISSUE THREAD

**Issue by MohammedSheikh** [DMU-CTEC2902/TeamHorus#57]
For all the films and directors on our website, would it be OK for you to create a folder (zipped) with all the JPG and PNG images required to render our webpages please?

Nothing much ,as long as the images are clear and represent the actors and directors.

And maybe you can just upload the folder to Github, so that myself, Callum, and Mwenya find it easy to acquire the images when developing our respective components on the website.

Thanks.

**Comment by FreddyJilson** [comment]
I have all the images of actors, directors and movies you require for the website contents.
Here is the zip file link. https://github.com/DMU-CTEC2902/TeamHorus/blob/ad902d76f9c0b1b95b8c5ad28c4cf6550c301e8c/MovieSite_Images.zip

or 

https://github.com/DMU-CTEC2902/TeamHorus/tree/master/MovieSite_Images

Thanks.
