### ISSUE TITLE
Foreign key constraint

### ISSUE THREAD

**Issue by MwenyaJunior** [DMU-CTEC2902/TeamHorus#59]
Hello, can't seem to update the database because of the foreign key constraint for User. This is the error shown, "Introducing FOREIGN KEY constraint 'FK_dbo.Comments_dbo.Users_UserID' on table 'Comments' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint. See previous errors."

**Comment by MohammedSheikh** [comment]
I have just fixed the error, hopefully it should work now.

**Comment by MwenyaJunior** [comment]
thanks, working now
