### ISSUE TITLE
Error in Configuration.cs for 'Movies' and 'Reviews'

### ISSUE THREAD

**Issue by MohammedSheikh** [DMU-CTEC2902/TeamHorus#61]
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Reviews_dbo.Movies_MovieID". The conflict occurred in database "MainSiteContext-20160413164240", table "dbo.Movies", column 'MovieID'.

**Comment by MwenyaJunior** [comment]
Strange that this error is being shown. Perhaps it could be due to a problem with the relationships between the tables? 

@FreddyJilson @EgleSc Could you please revisit the diagrams to ensure that the relationships are correct for the Movies and review table.

Thanks.
