### ISSUE TITLE
Team final meeting

### ISSUE THREAD

**Issue by FreddyJilson** [DMU-CTEC2902/TeamHorus#62]
Team members,
@EgleSc 
@MohammedSheikh 
@MwenyaJunior 
@Carvalth 

Its about time we finalize our work as the deadline is midnight on 3rd May. So in order to finish up things, we just need a meeting before the deadline so that we can make sure everything is working fine. For the system analysts it would be an opportunity to see the final system presented by the developers and it would also help in changing the documentation wherever necessary. The meeting will be tomorrow,  2nd May, 2016 (Monday) at 3pm. Tomorrow its a bank holiday, so we will meet at the library as the gateway house will be closed.

Thank you

**Comment by Carvalth** [comment]
I can't make it to the meeting today. However I will continue to update
work to github today.

Callum.

On Sun, May 1, 2016 at 6:48 PM, Freddy Jilson <notifications@github.com>
wrote:

> Team members,
> @EgleSc <https://github.com/EgleSc>
> @MohammedSheikh <https://github.com/MohammedSheikh>
> @MwenyaJunior <https://github.com/MwenyaJunior>
> @Carvalth <https://github.com/Carvalth>
>
> Its about time we finalize our work as the deadline is midnight on 3rd
> May. So in order to finish up things, we just need a meeting before the
> deadline so that we can make sure everything is working fine. For the
> system analysts it would be an opportunity to see the final system
> presented by the developers and it would also help in changing the
> documentation wherever necessary. The meeting will be tomorrow, 2nd May,
> 2016 (Monday) at 3pm. Tomorrow its a bank holiday, so we will meet at the
> library as the gateway house will be closed.
>
> Thank you
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/DMU-CTEC2902/TeamHorus/issues/62>
>



-- 
*Varle.C*
*New Solutions for Business*
*Business Advisor*

**Comment by EgleSc** [comment]
Where in library are we meeting?
